name: Deploy JSON File

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy JSON File
        run: |
          mkdir -p public
          cp app/English/en.json public/

      - name: Commit and Push Changes
        run: |
          git config --local user.email "bhapkarbhushan@gmail.com"
          git config --local user.name "Galact-os"
          git add public
          git commit -m "Deploy JSON file"
          git push
